# Generated by Django 5.1.6 on 2025-03-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencymodel",
            options={"ordering": ["-datetime"]},
        ),
    ]
